xiaolin/react-image-gallery

src/ImageGallery.react.jsx

code clean

---

src/ImageGallery.react.jsx

Fixes #12 to add support for specifying an initial image when gallery component is mounted

Add initial image support 

---

README.md
src/ImageGallery.react.jsx
src/ImageGallery.scss

I added the ability for the user to show the index. This was useful for me , it may not be useful to anybody else, so feel free to reject it if you dont want it in the codebase. I also made the separator configurable.

Added ability to show index

---

README.md
src/ImageGallery.react.jsx

Merged #31 and #32 and made the amends you requested.

Server rendering and alt tags

---

README.md
example/app.js
src/ImageGallery.jsx

Hi @xiaolin , here me again! I was working into a new and interesting feature for the image-gallery. Do you hear about srcSet? https://ericportis.com/posts/2014/srcset-sizes/.
The change that I did is about optimize image-gallery in different types of devices. For example, if you're using this gallery into a mobile with a high resolution you probably want to have a higher size image than a device with a lower resolution.
This is possible through the srcset and size attributes into img tag a new way to work with adaptive images.
Thanks a lot,
Greetings from Buenos Aires, Argentina.
Gaston.

Srcset attribute

---

README.md
example/app.js
src/ImageGallery.jsx

As per https://github.com/xiaolin/react-image-gallery/issues/57.

Add public getCurrentIndex() method

---

src/ImageGallery.jsx
src/image-gallery.scss

Hi xiaolin,
I added a capability that gives small labels below each thumbnail, it's taken as property and is optional to display. Please mention any opinions or do code changes on top of it.

Added capability to display labels for each thumbnail

---

src/ImageGallery.jsx

Add `type=button` to all buttons.

Add type=button to all buttons

---

README.md
src/ImageGallery.jsx

Implements https://github.com/xiaolin/react-image-gallery/issues/117. I kept it really simple.

Add ability to pass custom react component nav elements as props

---

src/ImageGallery.jsx

Fix for the issue with setState() on unmounted component #136

Fix issue #136

---

package.json
src/ImageGallery.jsx

Add debounce to window resize event

---

README.md
src/ImageGallery.jsx

In my project, we need the event to stop the movement of the slides. And I think it's important that it's in the code.
Thanks!

add onTouchMove event

---

src/ImageGallery.jsx

as a standalone gallery it would be useful to optionally support additional hooks for touch. what do you think?
https://facebook.github.io/react/docs/events.html#touch-events

Support additional synthetic events

---

src/ImageGallery.jsx

Fix IE fullscreen change event

---

src/ImageGallery.jsx

Addresses: https://github.com/xiaolin/react-image-gallery/issues/277

clearing transition timeout on unmount

---

src/ImageGallery.jsx
styles/scss/image-gallery-no-icon.scss
styles/scss/image-gallery.scss

Pull request by issue #294
New label view:

ISSUE-294 Fixed broken thumbnail label

---

src/ImageGallery.jsx

related #288 #320
* fix debounce unmount issue
* canceltion debounce
* fix lint error
Edit: I use gulp server example to reproduce and it work fine.

fix: cancel debounce when component unmount

---

src/ImageGallery.jsx

Replaced unicode underscore with regular

---

package-lock.json
src/ImageGallery.jsx

when you have the image more then one , it will give awarning

changing key

---

README.md
src/ImageGallery.jsx

Added height and width attribute to images and updated readme.

Added height and width attribute to images. NOT TESTED

---

README.md
src/ImageGallery.js

Add dimensions to thumbnails

---

package.json
yarn.lock

Build on React 18 and add it as a peer dependency.

Build on React 18

---

src/ImageGallery.js

Fix an issue when playing started automatically after changing interval or duration

Prevent start playing on interval or duration change

---

src/ImageGallery.js
styles/scss/image-gallery.scss

This is the fix for #651, I have renamed the right and left classes. In addition, I also rename the center classes.

Rename className for left, right, center

---

src/Item.js
src/SVG.js
src/SwipeWrapper.js

fix: defaultProps is deprecated

---

README.md
src/components/ImageGallery.jsx

Fixes #655 
deprecate item prop `bulletOnClick` 
add prop `onBulletClick`

[#655] Fixes slides overlap when there are only 2 images

---

README.md

PR #750 renamed the `app.js` to be `App.jsx`. This PR adjusts sources to changes.

Update example reference

---

package.json

Resolves https://github.com/xiaolin/react-image-gallery/issues/814

Export scss file in package.json
