build/image-gallery.js, src/ImageGallery.react.jsx
Added add/detachEvent calls as alternative to add/removeEventListener, to prevent errors in IE8.
Since React officially supports IE8 and [addEventListener polyfills have a tendency to break event handling][1] in React, it's nice when components support IE8 out of the box.
[1]: https://github.com/facebook/react/issues/3131#issuecomment-128732009
=> Don't break IE8 by assuming add/removeEventListener.

build/image-gallery.js, src/ImageGallery.react.jsx
I use this library in my website and I really like it. I added a condition in the rendering of the arrows since it doesn't make sense to keep them when there's one or zero images. Confuses the users.
=> Don't render arrows when there are less than two items

src/ImageGallery.react.jsx
Noticed this when using the component with dynamic images that allow browsing through multiple ImageGalleries. The images will end up with a class like "loadedloadedloadedloaded", depending on how many times the individual image was viewed, which can cause issues with the .loaded css class and prevent the image from being displayed.
=> Fixes 'loaded' class being added multiple times to lazy-loaded images

src/ImageGallery.react.jsx
If you change the ImageGallery items property dynamically, then the currentIndex retains its value. For example: if you have a gallery with 4 items that had its third image clicked/viewed last and then change the items property to another set of images, then it will try to display the third image again, as its currentIndex is still set to that value. 
This is not much of a problem if you are always using the same amount of images, it will just start with the currentIndex image instead of the first image, but if there are less images than currentIndex, then it will just display an empty space.
This pull request ensures that the currentIndex state gets reset whenever the items property has been set. If the startIndex property was set as well, then currentIndex will be reset to the …
=> Resets currentIndex on props.items change

src/ImageGallery.react.jsx
Adds a new optional defaultImage property, which is used for the main and thumbnail images if the image failed to load, e.g.: broken link. It requires the full path to the image.
Usage:
```
<ImageGallery
items={caseImages}
defaultImage='/img/default.jpg'
/>
```
This commit is based on the request in issue #11 
(I wanted to keep this out of the other recent pull request, since this is a feature addition.)
=> FEATURE: Adds defaultImage props, used as placeholder for invalid images

src/ImageGallery.react.jsx
I've added a prop called "disableScrolling" that will disable scrolling of the thumbnails. In my case, I have a CSS that layouts the thumbnails in multiple lines and no scrolling is required. 
I've also added some missing parentheses.
=> Prop for disabling scrolling of thumbnails

src/image-gallery.scss
Just a little nicety that allows for the setting of `$ig-*` variables earlier in the code, so that this is possible:
_variables.scss
```scss
$custom-roses: red;
$custom-violets: blue;
...
// Image gallery
$ig-white: whitesmoke;
$ig-blue: darken($custom-violets, 5%);
```
_base.scss
```scss
@import 'variables';
@import '~react-image-gallery/src/image-gallery';
```
Thanks for your work! It's a huge help.
=> Make SCSS variables overridable

src/ImageGallery.jsx
Fix for the issue where a 2-image gallery would cause the slider to go in the wrong direction.
=> Fix Issue #54: Unexpected sliding direction in a 2-image gallery

package.json, src/ImageGallery.jsx
This PR adds the possibility to specify a custom `renderItem` function either as a prop or as a key in the item objects. If no renderItem function is specified the item is rendered as before.
I also added a build entry in the `package.json` so you don't have to install gulp globally to build the package.
=> Add possibility to specify custom renderItem function 

README.md
Quick fix, just a few missing commas that were making the example code unrunnable.
=> Fix syntax error in readme example

src/ImageGallery.jsx, styles/scss/image-gallery.scss
Currently on master, the UI elements (R and L arrows, bullets) are not "focusable" because the `<a>` has no `href` attribute. If they are not "focusable", they are not accessible via a mouse-less interface, a requirement for ADA compliance. More information [here](http://webaim.org/techniques/keyboard/) and [here](https://www.nngroup.com/articles/keyboard-accessibility/)
This PR updates the the right and left arrows, bullets to use `<button>`s instead of `<a>`s and `<li>`s, respectively. The reason is three-fold: 
1. `<button>` is more semantically correct.
2. `<button>`s are "focusable".
3. While a `<button>` has focus, hitting enter acts like a click.
I'm not sure this is the best approach or best styling. I just wanted to flag it as a problem as well as offer a potential solution.
=> Change R and L arrows, bullets to HTML buttons for accessibility.

README.md, src/ImageGallery.jsx
Fixes #120 
This adds a new prop that will enable you to render custom controls/elements within the currently displayed image.
Should I add this to the example? Not exactly sure if that makes sense, the README should explain everything I think.
=> Add func prop to render custom controls

src/ImageGallery.jsx
Striving for compliance with WCAG 2.0, I added a few tweaks (attributes) to help screen readers and other assistive technologies. Attempting to make `react-image-gallery` fulfill Success Criteria 4.2.1 of WCAG 2.0:
https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html
- `aria-label` says what a particular button / UI element does
- `role` tells it to treat an element like a different element (`<a>` like a `<button>`, `<ul>` like a `<nav>`
- `aria-pressed` is for toggles
- `aria-live` is for content that updates "live"
More info: 
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute
http://accessibility.athena-ict.com/aria/examples/carousel.shtml
=> Additional Accessibility Tweaks

src/ImageGallery.jsx
Run into small problem with gallery when trying to update component with smaller array of images - it shows nothing and counter looks like "4/3". 
This is a quick fix for emptiness in such case.
=> Slide to start when currentIndex outside of new images

src/ImageGallery.jsx
When you unmount component during resize event, you can get warning:
"Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ImageGallery component."
I just added debounce.cancel() in componentWillUnmoun
=> Remove handleResize on unmount

README.md, src/ImageGallery.jsx
I have found the default swipe threshold of 30 to be insufficient and would like to be able to control how sensitive the gallery's swipe detection is.
=> Adding prop for swipeThreshold

README.md, src/ImageGallery.jsx
It stops propagation of touch events of underlying Swipeable component, useful when there are nested swipeable views.
=> add stopPropagation optional prop

README.md, src/ImageGallery.jsx
There is an issue on mobile when swiping, it tries to scroll up/down at the same time.
It would be godd to expose the `preventDefaultTouchmoveEvent` prop from `react-swipeable` so you have the option to prevent the browser's touchmove event if it is not desired.
=> expose preventDefaultTouchmoveEvent prop

README.md, example/app.js, package.json, src/ImageGallery.jsx
First off, thanks for making this great gallery component and taking the time to maintain it! 
This is only a small PR: 
**What:** A custom className prop. This will optionally add an extra className to the root node of the gallery. 
**Why:** Sometimes you need to target an element by className (css, check visibility...).  Targeting the default class of the component is not safe because what you can't control might change. Adding yet another div to wrap the component would be unnecessary if you could set a custom class.
=> added a custom className prop

src/ImageGallery.jsx
added 50ms to _onSliding. when infinite is set to true and the user holds down the arrow key, the transitioning slides don't behave as expected. the extra 50ms delays changing isTransitioning in state which fixes the transitioning problem
=> added 50ms to _onSliding

src/ImageGallery.jsx
This resolves a violation in the Firefox AInspector extension, used to test accessibility rules:
=> Add role="button" with onClick prop to fix a11y violation

package.json, src/ImageGallery.jsx
- update `react-swipeable` to `v4.2.2` to clean up no-op functions
- https://github.com/dogfessional/react-swipeable/tree/v4.2.2
closes #268
=> update react-swipeable, clean up no-op funcs

src/ImageGallery.jsx
This PR allows usage of the `type` attribute to be used in conjunction with the `imageSet` property. 
[`<source>` docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture)
=> allow imageSet `source` attribute

src/ImageGallery.jsx
Github issue: #375 
I guess this is the correct behavior for `onSlide`. It should be called after slide transition.
By the way, do we need to mention this in README?
=> Trigger onSlide after slide transition

package.json
This change enables `postcss-import` and other tools to infer which CSS file is the correct one to import when referencing the module name. This means users can do `@import 'react-image-gallery';` and it will import the correct stylesheet. This change should make it a _little_ bit easier for people to get started using `react-image-gallery`.
More on the `style` attribute: https://jaketrent.com/post/package-json-style-attribute/
=> Add `style` to package.json

package.json, src/ImageGallery.jsx
- closes #321 
- closes https://github.com/dogfessional/react-swipeable/issues/128
...
I found some time, 🎉 and I know we discussed possibly just removing `react-swipeable` in #321, but opened this to see what updating to v5 would look like.
=> update react-swipeable to v5

README.md, example/app.js, src/ImageGallery.jsx
If accepted, will resolve #466. This restores the previous (`<= v0.8.12`) functionality of the `onSlide` callback by naming it `onBeforeSlide`, as it is called just before the slide transition occurs.
=> Add onBeforeSlide callback

src/ImageGallery.jsx
In case when we're going to show thumbnails dynamically eg render with `showThumbnails=false` and then we change this to `showThumbnails=true` - thumbnails are appearing but handleResize is not being triggered and translate/translate3d for `image-gallery-thumbnails-container` is not working.
=> fix-show-thumbnails-dynamically

src/ImageGallery.jsx
Original issue:
1. set useBrowswerFullScreen to false
2. Add an iframe to you slides
3. Toggle slider full screen
4. Toggle full screen in iframe (like youtube full screen)
5. Press escape or collapse youtube full screen
Actual: slider will stuck in full screen mode
This happens because onScreenChange handler assumes that you closed full screen, however this not true in case if you use css full screen
=> Fix on screen change

src/ImageGallery.jsx
Fix for #525 
Adds `aria-label` to the item renderer for `image-gallery-slide`. Because of `role="button"` it is an accessibility violation to not have an aria-readable label. This fixes that problem.
I have used VSCode and it insists on updating the formatting on the other files. This seems consistent to me so it should probably be kept.
=> Add aria label to image-gallery-slide

package.json
This pull request is intended to fix the following warning,
react-image-gallery@1.0.8" has incorrect peer dependency "react@^16.0.0".
=> Adding react v17 as a peer dependency!

README.md, src/ImageGallery.js, src/Item.js
Add `loading` param to all image tags.
The `loading` param can be used in img tags to use native lazy load by adding `loading=“lazy”`. This means browsers will only start loading image when it appears on the screen. Nowadays Google Lighthouse / Insights scores pages negatively if images below the fold are not lazyloaded.
Changes:
- Add “loading” parameter to item. Will either default to “eager” (=html default, preserves existing behavior), or user can set it to “lazy”
- Add “thumbnailLoading” parameter to item. Same behavior, user can set thumbnails to lazyload
- Add mentions of these new parameters to readme
I would’ve like to add a test case for this, but the current test command & setup do not seem to work. Something about Jest not liking one of lodash dependencies. I checked this with …
=> Image & thumbnail: add loading param

src/ImageGallery.js
While running an accessibility test on a project using this package we found the following error: `aria-label attribute is not well supported on a div with no valid role attribute`.
You could simply add a `role="navigation"` to the div, but changing the `div` to `nav` will do that and be more semantically correct.
=> Wrap thumbnails in `nav` tag to get proper ARIA role

src/ImageGallery.js
This PR resolves a known issue mentioned in https://github.com/xiaolin/react-image-gallery/issues/655
When there are only 2-3 images in the gallery, clicking on thumbnail causes the wrong image to slide over current image.
=> #655 Fixed: images slide above each other

example/App.jsx, src/components/ImageGallery.jsx
fixed issue https://github.com/xiaolin/react-image-gallery/issues/767. Fixed to bug of left/right navigators only allowing to scroll to first and last image in RTL mode. Now both nav buttons allow slide in the correct direction.
=> FIX: #767 . 
